[build-system]
requires = ["setuptools>=61.0", "wheel", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "cost-overrun-predictor"
version = "0.1.0"
requires-python = "==3.9.*"

[tool.setuptools]
py-modules = [] 