[build-system]
requires = ["setuptools>=68.0.0", "wheel>=0.41.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cost-overrun-predictor"
version = "0.1.0"
requires-python = ">=3.12"

[tool.setuptools]
py-modules = [] 