[server]
port = 8501
address = "0.0.0.0"
headless = true

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501

[runner]
fastReruns = true

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

